package com.test.palmapi.ui.theme

import androidx.compose.ui.graphics.Color

object CelestialPalette {
    val md_theme_dark_primary = Color(0xFFAEC6FF)
    val md_theme_dark_onPrimary = Color(0xFF002E6A)
    val md_theme_dark_primaryContainer = Color(0xFF11448F)
    val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
    val md_theme_dark_secondary = Color(0xFFAEC6FF)
    val md_theme_dark_onSecondary = Color(0xFF002E6A)
    val md_theme_dark_secondaryContainer = Color(0xFF11448F)
    val md_theme_dark_onSecondaryContainer = Color(0xFFD8E2FF)
    val md_theme_dark_tertiary = Color(0xFFA3C9FF)
    val md_theme_dark_onTertiary = Color(0xFF00315C)
    val md_theme_dark_tertiaryContainer = Color(0xFF004883)
    val md_theme_dark_onTertiaryContainer = Color(0xFFD3E3FF)
    val md_theme_dark_error = Color(0xFFFFB4AB)
    val md_theme_dark_errorContainer = Color(0xFF93000A)
    val md_theme_dark_onError = Color(0xFF690005)
    val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
    val md_theme_dark_background = Color(0xFF001F25)
    val md_theme_dark_onBackground = Color(0xFFA6EEFF)
    val md_theme_dark_surface = Color(0xFF001F25)
    val md_theme_dark_onSurface = Color(0xFFA6EEFF)
    val md_theme_dark_surfaceVariant = Color(0xFF44474F)
    val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
    val md_theme_dark_outline = Color(0xFF8E9099)
    val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
    val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
    val md_theme_dark_inversePrimary = Color(0xFF325DA8)
    val md_theme_dark_shadow = Color(0xFF000000)
    val md_theme_dark_surfaceTint = Color(0xFFAEC6FF)
    val md_theme_dark_outlineVariant = Color(0xFF44474F)
    val md_theme_dark_scrim = Color(0xFF000000)


    val seed = Color(0xFF0D1B35)
}


object RetrofuturistPalette {
    val md_theme_dark_primary = Color(0xFFC2C1FF)
    val md_theme_dark_onPrimary = Color(0xFF1A01A6)
    val md_theme_dark_primaryContainer = Color(0xFF352EBA)
    val md_theme_dark_onPrimaryContainer = Color(0xFFE2DFFF)
    val md_theme_dark_secondary = Color(0xFFFFA9FB)
    val md_theme_dark_onSecondary = Color(0xFF58045E)
    val md_theme_dark_secondaryContainer = Color(0xFF732477)
    val md_theme_dark_onSecondaryContainer = Color(0xFFFFD6F9)
    val md_theme_dark_tertiary = Color(0xFFFFB1C1)
    val md_theme_dark_onTertiary = Color(0xFF66002A)
    val md_theme_dark_tertiaryContainer = Color(0xFF861C40)
    val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DF)
    val md_theme_dark_error = Color(0xFFFFB4AB)
    val md_theme_dark_errorContainer = Color(0xFF93000A)
    val md_theme_dark_onError = Color(0xFF690005)
    val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
    val md_theme_dark_background = Color(0xFF2A1800)
    val md_theme_dark_onBackground = Color(0xFFFFDDB6)
    val md_theme_dark_surface = Color(0xFF2A1800)
    val md_theme_dark_onSurface = Color(0xFFFFDDB6)
    val md_theme_dark_surfaceVariant = Color(0xFF47464F)
    val md_theme_dark_onSurfaceVariant = Color(0xFFC8C5D0)
    val md_theme_dark_outline = Color(0xFF918F9A)
    val md_theme_dark_inverseOnSurface = Color(0xFF2A1800)
    val md_theme_dark_inverseSurface = Color(0xFFFFDDB6)
    val md_theme_dark_inversePrimary = Color(0xFF4E4AD2)
    val md_theme_dark_shadow = Color(0xFF000000)
    val md_theme_dark_surfaceTint = Color(0xFFC2C1FF)
    val md_theme_dark_outlineVariant = Color(0xFF47464F)
    val md_theme_dark_scrim = Color(0xFF000000)


    val seed = Color(0xFF362FBB)

}

object CornSilkPalette {

    val md_theme_dark_primary = Color(0xFFFFB2BB)
    val md_theme_dark_onPrimary = Color(0xFF670022)
    val md_theme_dark_primaryContainer = Color(0xFF910033)
    val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9DD)
    val md_theme_dark_secondary = Color(0xFFFFB1C0)
    val md_theme_dark_onSecondary = Color(0xFF660029)
    val md_theme_dark_secondaryContainer = Color(0xFF8B113D)
    val md_theme_dark_onSecondaryContainer = Color(0xFFFFD9DF)
    val md_theme_dark_tertiary = Color(0xFFFFB2BD)
    val md_theme_dark_onTertiary = Color(0xFF5F1127)
    val md_theme_dark_tertiaryContainer = Color(0xFF7D293C)
    val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DD)
    val md_theme_dark_error = Color(0xFFFFB4AB)
    val md_theme_dark_errorContainer = Color(0xFF93000A)
    val md_theme_dark_onError = Color(0xFF690005)
    val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
    val md_theme_dark_background = Color(0xFF1C1D00)
    val md_theme_dark_onBackground = Color(0xFFE6E971)
    val md_theme_dark_surface = Color(0xFF1C1D00)
    val md_theme_dark_onSurface = Color(0xFFE6E971)
    val md_theme_dark_surfaceVariant = Color(0xFF524344)
    val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C3)
    val md_theme_dark_outline = Color(0xFF9F8C8E)
    val md_theme_dark_inverseOnSurface = Color(0xFF1C1D00)
    val md_theme_dark_inverseSurface = Color(0xFFE6E971)
    val md_theme_dark_inversePrimary = Color(0xFFBB0946)
    val md_theme_dark_shadow = Color(0xFF000000)
    val md_theme_dark_surfaceTint = Color(0xFFFFB2BB)
    val md_theme_dark_outlineVariant = Color(0xFF524344)
    val md_theme_dark_scrim = Color(0xFF000000)


    val seed = Color(0xFFFB4570)

}

object AquaBlissPalette {
    val md_theme_dark_primary = Color(0xFF57DBC4)
    val md_theme_dark_onPrimary = Color(0xFF00372F)
    val md_theme_dark_primaryContainer = Color(0xFF005046)
    val md_theme_dark_onPrimaryContainer = Color(0xFF77F8E0)
    val md_theme_dark_secondary = Color(0xFF05DED0)
    val md_theme_dark_onSecondary = Color(0xFF003733)
    val md_theme_dark_secondaryContainer = Color(0xFF00504B)
    val md_theme_dark_onSecondaryContainer = Color(0xFF4AFBEC)
    val md_theme_dark_tertiary = Color(0xFFFFB0CD)
    val md_theme_dark_onTertiary = Color(0xFF640039)
    val md_theme_dark_tertiaryContainer = Color(0xFF8D0052)
    val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E4)
    val md_theme_dark_error = Color(0xFFFFB4AB)
    val md_theme_dark_errorContainer = Color(0xFF93000A)
    val md_theme_dark_onError = Color(0xFF690005)
    val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
    val md_theme_dark_background = Color(0xFF001849)
    val md_theme_dark_onBackground = Color(0xFFDBE1FF)
    val md_theme_dark_surface = Color(0xFF001849)
    val md_theme_dark_onSurface = Color(0xFFDBE1FF)
    val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
    val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
    val md_theme_dark_outline = Color(0xFF89938F)
    val md_theme_dark_inverseOnSurface = Color(0xFF001849)
    val md_theme_dark_inverseSurface = Color(0xFFDBE1FF)
    val md_theme_dark_inversePrimary = Color(0xFF006B5D)
    val md_theme_dark_shadow = Color(0xFF000000)
    val md_theme_dark_surfaceTint = Color(0xFF57DBC4)
    val md_theme_dark_outlineVariant = Color(0xFF3F4946)
    val md_theme_dark_scrim = Color(0xFF000000)


    val seed = Color(0xFFBCECE0)

}

